version: "3"

services:
  next-app:
    container_name: next-app
    build:
      context: ../frontend/
      dockerfile: ../docker_configs/frontend.dev.Dockerfile

    env_file:
      - ../.env.production.local
    volumes:
      - ../frontend/src:/app/src
      - ../frontend/public:/app/public
    restart: always
    ports:
      - 3000:3000
    networks:
      - app_network
    
  djangoapp:
    container_name: djangoapp
    build:
      context: ../backend/
      dockerfile: ../docker_configs/backend.Dockerfile
    ports:
      - 8000:8000
    networks:
      - app_network
    env_file:
      - ../.env.production.local

networks:
  app_network:
    external: true
