version: "3"

services:
  flask-app:
    container_name: flask-app
    build:
      context: ../frontend/
      dockerfile: ../docker_configs/frontend.Dockerfile
    ports:
      - 5000:5000
    networks:
      - app_network
    env_file:
      - ../.env.production.local

  django-app:
    container_name: django-app
    build:
      context: ../backend/
      dockerfile: ../docker_configs/backend.Dockerfile
    ports:
      - 8000:8000
    networks:
      - app_network
    env_file:
      - ../.env.production.local

networks:
  app_network:
    external: true
